apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.deti:5000/egs-ressellr/frontend:v2.9
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          value: frontend-db-service
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: frontend
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: ressellr
      volumes:
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-frontend
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: egs-ressellr
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


