version: '3.7'
networks:
  frontend-network:
    driver: bridge

services:
  frontend:
    build: .
    hostname: frontend
    container_name: frontend
    environment:
      DB_HOST: frontend_DB
      DB_NAME: frontenddb
      DB_USER: frontend
      DB_PASSWORD: password
      DB_PORT: 3306
    depends_on:
      - frontend_DB
    ports:  
      - "80:80"
    networks:
      - frontend-network
    links:
      - frontend_DB
    restart: on-failure

  frontend_DB:
    image: mariadb
    restart: always
    container_name: frontend_DB
    environment:
      MYSQL_DATABASE: frontenddb
      MYSQL_USER: frontend
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - frontend-network

volumes:
  frontend_data: