version: '3.7'
networks:
  frontend_network:
    driver: bridge
services:
  frontend:
    image: frontend:1.0
    hostname: frontend
    container_name: frontend
    environment:
      MARIADB_DATABASE: 'project'
      MARIADB_USER: 'username'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'toor'
    depends_on:
      - frontend_DB
    ports:  
      - "80:80"
    networks:
      - frontend_network
    links:
      - frontend_DB
    volumes:
      - ./:/app

  frontend_DB:
    image: mariadb:10.7
    restart: always
    hostname: frontend_DB
    container_name: frontend_DB
    environment:
      MARIADB_DATABASE: 'project'
      MARIADB_USER: 'username'
      MARIADB_PASSWORD: 'password'
      MARIADB_ROOT_PASSWORD: 'toor'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - frontend_network

volumes:
  frontend_data: