# Define a 'Persistent Volume Claim' (PVC) for MariaDB Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-frontend
  namespace: egs-ressellr
spec:
  accessModes:
    - ReadWriteOnce   
  resources:
    requests:
      storage: 500Mi    
  storageClassName: longhorn

---
# Configure 'Deployment' of MariaDB server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-db
  namespace: egs-ressellr
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend-db
  template:
    metadata:
      labels: 
        app: frontend-db
    spec:
      containers:
      - name: frontend-db
        image: mariadb:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_USER
          value: "frontend"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE 
          value: "ressellr"
        volumeMounts:
        - name: mysql-storage-frontend
          mountPath: /var/lib/mysql
        - name: mysql-initdb-frontend
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage-frontend
        persistentVolumeClaim:
          claimName: mysql-pvc-frontend
      - name: mysql-initdb-frontend
        configMap:
          name: mysql-initdb-frontend

---
# Define a 'Service' to expose MySQL to other services
apiVersion: v1
kind: Service
metadata:
  name: frontend-db-service
  namespace: egs-ressellr
spec:
  selector:
    app: frontend-db
  ports:
  - protocol: TCP
    targetPort: 3306
    port: 3306
