---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: egs-ressellr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: longhorn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-db
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-db
  template:
    metadata:
      labels:
        app: frontend-db
    spec:
      containers:
      - name: frontend-db
        image: mariadb:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "Resellrfrontend"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-frontend
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-db-service
spec:
  selector:
    app: frontend-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306