apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
      - name: payment-app
        image: registry.deti:5000/egs-ressellr/payment:v1 #replace with your payment application image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---

# Payment App Service
apiVersion: v1
kind: Service
metadata:
  name: payment-app
  namespace: egs-ressellr
spec:
  type: ClusterIP
  selector:
    app: payment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
