apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: payment-service
        image: registry.deti:5000/egs-ressellr/payment:v6.21 #replace with your payment application image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---

# Payment App app
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: egs-ressellr
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
