apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
      - name: payment-app
        image: registry.deti:5000/egs-ressellr/payment:latest #replace with your payment application image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000

---

# Payment App Service
apiVersion: v1
kind: Service
metadata:
  name: payment-app
spec:
  type: NodePort
  selector:
    app: payment-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001 # select an available port from 30000-32767

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ressellr
  namespace: egs-ressellr
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-ressellr.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port: 
              number: 4000