# Define a 'Persistent Volume Claim' (PVC) for MariaDB Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  namespace: egs-ressellr

  labels:
    app: mariadb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   
  resources:
    requests:
      storage: 100Mi    
  storageClassName: longhorn

---
# Configure 'Deployment' of MariaDB server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockdb-deployment
  namespace: egs-ressellr

  labels:
    app: stockdb
    tier: database
spec:
  selector: 
    matchLabels:
      app: stockdb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: stockdb
        tier: database
    spec:
      containers:
      - name: stockdb
        image: registry.deti:5000/egs-ressellr/stockdb:v1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: stock
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE 
          value: stockdb
        #volumeMounts:
        # - name: data-volume
        #   mountPath: /var/lib/mysql
        # - name : init-script
        #   mountPath: /docker-entrypoint-initdb.d/init.sql
  
      volumes:
      # # - name: init-script
      # #   hostPath:
      # #     path: /home/miguel/Documents/stockAPI/db/init.sql
      # - name: data-volume # Mounting 'volume' to the container
      #   hostPath:
      #     path: /home/miguel/Documents/stockAPI/data/mysql
      - name: mariadb-persistent-storage # Obtaining 'volume' from PVC
        persistentVolumeClaim:
          claimName: mariadb-pv-claim

---
# Define a 'Service' to expose MySQL to other services
apiVersion: v1
kind: Service
metadata:
  name: stockdb 
  namespace: egs-ressellr
  labels:
    app: stockdb
    tier: database
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector: 
    app: stockdb
    tier: database
