version: '3.3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: stockdb
      MYSQL_USER: stock
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3307:3306"
 
  app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: stockdb
      DB_USER: stock
      DB_PASSWORD: password
      DB_PORT: 3306

    restart: on-failure

    ports:
      - "8000:8000"
    depends_on:
      - db