FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

ENV PYTHONUNBUFFERED=1

COPY ./ .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8000
#set environment
#ENV NUXT_HOST=0.0.0.0

#ENV NUXT_PORT=$PORT

#ENV PROXY_API=$PROXY_API

#ENTRYPOINT ["python", "main.py"]

# build -> docker build -t frontend -f deploy\Dockerfile.frontend .\frontend
# run -> docker run --rm -it -p 8080:8080 frontend 