FROM python:alpine3.17

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade -r requirements.txt

COPY ./ .

EXPOSE 5000

CMD [ "python", "googleAuth.py"]

# build -> docker build -t auth:1.0 -f deploy\Dockerfile.auth .\authentication
# run -> docker run --rm -p 5000:5000 auth:1.0