FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

ENV PYTHONUNBUFFERED=1

WORKDIR /frontend

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./ .

EXPOSE 80

CMD ["python", "main.py"]

# build -> docker build -t frontend:1.0 -f deploy\Dockerfile.frontend .\frontend
# run -> docker run --rm -p 80:80 frontend:1.0