FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./ .

EXPOSE 80

CMD ["python", "main.py"]

# build -> docker build -t frontend -f deploy\Dockerfile.frontend .\frontend
# run -> docker run --rm -it -p 80:80 frontend:1.0