FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y nodejs && apt install -y mysql-server && apt install -y npm

COPY . .

RUN service mysql start
RUN mysql
RUN source ../db/dbInit.sql

RUN npm install

CMD [ "npm", "start" ]