version: '1.0'

services:
  frontend:
    build: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - frontend_DB
      - messages
      - stock
      - payment
      - authentication
  
  authentication:
    build: Dockerfile.auth
    ports:
      - "5000:5000"
  messages:
    build: Dockerfile.messages
    ports:
      - "3000:3000"
    depends_on:
      - messages_DB

  payment:
    build: Dockerfile.payment
    ports:
      - "4000:4000"
    

  stock:
    build: Dockerfile.stock
    ports:
      - "8080:8080"

  frontend_DB:
    image: frontenddb
    restart: always
    volumes: 
      - ./data:/data
    ports:
      - "3306:3306"
     

  messages_DB:
    build: Dockerfile.messagesDB

  stock_DB:
    build: Dockerfile.stockDB

secrets:
  cert:
    file: ./config/ssl_cert/certificate.pem
  
  key:
    file: ./config/ssl_cert/privatekey.pem

volumes:
  frontenddb:
  messagesdb:
  stockdb: