version: '3.7'
networks:
  frontend_network:
    driver: bridge
services:
  frontend:
    image: frontend:1.0
    hostname: frontend
    container_name: frontend
    environment:
      MYSQL_DATABASE: frontend
      MYSQL_USER: frontend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: frontend
    depends_on:
      - frontend_DB
    ports:  
      - "80:80"
    networks:
      - frontend_network
    volumes:
      - ./:/app

  frontend_DB:
    image: mysql:latest
    hostname: frontend_DB
    container_name: frontend_DB
    restart: always
    environment:
      MYSQL_DATABASE: frontend
      MYSQL_USER: frontend
      MYSQL_PASSWORD: frontend
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ../frontend:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - frontend_network

volumes:
  frontend_data: