FROM alpine:latest

RUN apk update && apk add mysql mysql-client

COPY database.db /tmp/database.db

RUN /etc/init.d/mysqld start && mysql -u root -e "CREATE DATABASE mydb" && mysql -u root mydb < /tmp/database.db

EXPOSE 3306

CMD ["mysqld", "--user=mysql", "--datadir=/var/lib/mysql", "--port=3306", "--bind-address=0.0.0.0"]
