version: '3.9'

networks:
  kong-net:
    driver: bridge
services:
  kong-database:
    image: postgres:9.6
    restart: always
    hostname: kong-database
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-bootstrap:
    image: kong:latest
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    restart: on-failure
    networks:
      - kong-net
    links:
      - kong-database
  
  kong:
    image: kong:latest
    restart: always
    hostname: kong
    container_name: kong
    depends_on:
      - kong-database
      - kong-bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_GUI_URL: http://localhost:8002
    command: kong start
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
    networks:
      - kong-net