apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: messages
        image: registry.deti:5000/egs-ressellr/messages:v1.5
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          value: messages-db-service
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "ResellrMessages"
      volumes:
      - name: messages-storage
        persistentVolumeClaim:
          claimName: mysql-pvc-messages
---

apiVersion: v1
kind: Service
metadata:
  name: messages-service
  namespace: egs-ressellr
spec:
  selector:
    app: messages
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000