version: '3.7'

services:
  messages:
    build: .
    environment:
      DB_HOST: messages_DB
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: ResellrMessages
    depends_on:
      - messages_DB
    ports:
      - "4000:3000"

  messages_DB:
    image: mariadb:10.7
    environment:
      MYSQL_DATABASE: 'ResellrMessages'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./data:/var/lib/mysql
      - ./db/dbInit.sql:/docker-entrypoint-initdb.d/dbInit.sql
