# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: egs-ressellr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: registry.deti:5000/egs-ressellr/authentication-service:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


---

# Authentication Service
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: egs-ressellr
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: authentication-service


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ressellr
  namespace: egs-ressellr
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-ressellr.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authentication-service
            port: 
              number: 80