# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: registry.deti:5000/egs-ressellr/authentication:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000


---

# Authentication Service
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: egs-ressellr
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7000
    # nodePort: 32001 # acede a este endereço de fora do cluster
  selector:
    app: authentication-service
