# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: egs-ressellr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: authentication-service
        image: registry.deti:5000/egs-ressellr/authentication:v4.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000


---

#Authentication Service
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: egs-ressellr
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7000
  selector:
    app: authentication-service
